on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Digger project to perform destroy on'
        required: true
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: digger destroy
      uses: diggerhq/digger@v0.4.6
      with:
        mode: manual
        command: "digger destroy"
        project: "${{ inputs.project }}"
        setup-google-cloud: true
        google-auth-credentials: '${{ secrets.GCP_CREDENTIALS }}'
        setup-terragrunt: true
        terragrunt-version: 0.63.5
        no-backend: true
      env:
        LOCK_PROVIDER: gcp
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_STORAGE_BUCKET: floorball-fantasy-bucket
        TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}