name: Digger

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  plan:
    permissions: write-all
    name: Digger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        create_credentials_file: true
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: digger run
      uses: diggerhq/digger@v0.4.6
      with:
        setup-google-cloud: true
        google-auth-credentials: '${{ secrets.GCP_CREDENTIALS }}'
        setup-terragrunt: true
        terragrunt-version: 0.63.5
        no-backend: true
      env:
        LOCK_PROVIDER: gcp
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_STORAGE_BUCKET: deployment-433913-bucket
        TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}